// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package kz.buronahodok.domain;

import kz.buronahodok.domain.LostAndFoundDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LostAndFoundDataOnDemand_Roo_Configurable {
    
    declare @type: LostAndFoundDataOnDemand: @Configurable;
    
}
