// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package kz.buronahodok.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import kz.buronahodok.domain.LostAndFound;
import kz.buronahodok.domain.LostAndFoundDataOnDemand;
import kz.buronahodok.domain.LostAndFoundIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LostAndFoundIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LostAndFoundIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LostAndFoundIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LostAndFoundIntegrationTest: @Transactional;
    
    @Autowired
    LostAndFoundDataOnDemand LostAndFoundIntegrationTest.dod;
    
    @Test
    public void LostAndFoundIntegrationTest.testCountLostAndFounds() {
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to initialize correctly", dod.getRandomLostAndFound());
        long count = LostAndFound.countLostAndFounds();
        Assert.assertTrue("Counter for 'LostAndFound' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LostAndFoundIntegrationTest.testFindLostAndFound() {
        LostAndFound obj = dod.getRandomLostAndFound();
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to provide an identifier", id);
        obj = LostAndFound.findLostAndFound(id);
        Assert.assertNotNull("Find method for 'LostAndFound' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'LostAndFound' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LostAndFoundIntegrationTest.testFindAllLostAndFounds() {
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to initialize correctly", dod.getRandomLostAndFound());
        long count = LostAndFound.countLostAndFounds();
        Assert.assertTrue("Too expensive to perform a find all test for 'LostAndFound', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<LostAndFound> result = LostAndFound.findAllLostAndFounds();
        Assert.assertNotNull("Find all method for 'LostAndFound' illegally returned null", result);
        Assert.assertTrue("Find all method for 'LostAndFound' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LostAndFoundIntegrationTest.testFindLostAndFoundEntries() {
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to initialize correctly", dod.getRandomLostAndFound());
        long count = LostAndFound.countLostAndFounds();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<LostAndFound> result = LostAndFound.findLostAndFoundEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'LostAndFound' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'LostAndFound' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LostAndFoundIntegrationTest.testFlush() {
        LostAndFound obj = dod.getRandomLostAndFound();
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to provide an identifier", id);
        obj = LostAndFound.findLostAndFound(id);
        Assert.assertNotNull("Find method for 'LostAndFound' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLostAndFound(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'LostAndFound' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LostAndFoundIntegrationTest.testMergeUpdate() {
        LostAndFound obj = dod.getRandomLostAndFound();
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to provide an identifier", id);
        obj = LostAndFound.findLostAndFound(id);
        boolean modified =  dod.modifyLostAndFound(obj);
        Integer currentVersion = obj.getVersion();
        LostAndFound merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'LostAndFound' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LostAndFoundIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to initialize correctly", dod.getRandomLostAndFound());
        LostAndFound obj = dod.getNewTransientLostAndFound(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'LostAndFound' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'LostAndFound' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LostAndFoundIntegrationTest.testRemove() {
        LostAndFound obj = dod.getRandomLostAndFound();
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'LostAndFound' failed to provide an identifier", id);
        obj = LostAndFound.findLostAndFound(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'LostAndFound' with identifier '" + id + "'", LostAndFound.findLostAndFound(id));
    }
    
}
